### PR TITLE
Improved the main.py file.

### PR DESCRIPTION
**Pull request by ghost**
What it does, is basically -

We create an empty dictionary.
After that, we have two values, the maximumInputIndex and the currentInputIndex, the maxmiumInputIndex declares how many lines the todo file will have, and the currentInputIndex variable holds the current input shown(so if it was 1. input, it would be index 1), and we have a while loop, where the currentInputIndex is incremented by 1, and then, the dictionary is appended a key and a value, the currentInputIndex, and the actual text.

In the end, we loop through the keys and values, and we write them down.
Overall simpler solution so you don't have to do all that dirty variable stuff.

Sincerely,
IdrizP

### CODE REVIEW

**Comment by RDIL** [comment]
I would merge if you could fix conflicts

**Comment by RDIL** [comment]
Never mind let me fix the issue on my end.  Be back in a few.

**Comment by ghost** [comment]
Alright /shrug

**Comment by RDIL** [comment]
Had to recreate main.py with your code to resolve conflicts.

**Comment by RDIL** [comment]
@PelajTech do you think I should release it as v2.0 or v1.1?

**Pull request merged**
